export class survey {
	constructor(
        public id : number,
		public idpregunta : number,
		public idrespuestaOrigen : number,
		public nivel : number,
		public respuesta : string,
		public pregunta : string,
		public idrespuesta1 : number,
		public idrespuesta2 : number,
		public idrespuesta3 : number,
		public idrespuesta4 : number,
		public idrespuesta5 : number,
		public idrespuesta6 : number,
		public idrespuesta7 : number,
		public idrespuesta8 : number,
		public idrespuesta9 : number,
		public idrespuesta10 : number,
		public idSubrespNivel11 : number,
		public idSubrespNivel12 : number,
		public idSubrespNivel211 : number,
		public idSubrespNivel212 : number,
		public idSubrespNivel221: number,
		public idSubrespNivel222 : number,
		public idSubrespNivel3111 : number,
		public idSubrespNivel3112 : number,
		public idSubrespNivel3121 : number,
		public idSubrespNivel3122 : number,
		public idSubrespNivel3211 : number,
		public idSubrespNivel3212 : number,
		public idSubrespNivel3221 : number,
		public idSubrespNivel3222 : number,
		public idSubrespNivel41111 : number,
		public idSubrespNivel41112 : number,
		public idSubrespNivel41121 : number,
		public idSubrespNivel41122 : number,
		public idRespuesta : number,
		public idSubrespuesta : number,
		
	) { }
}